set(_AMENT_PACKAGE_NAME "dofbot_info")
set(dofbot_info_VERSION "0.0.0")
set(dofbot_info_MAINTAINER "root <1324760365@qq.com>")
set(dofbot_info_BUILD_DEPENDS )
set(dofbot_info_BUILDTOOL_DEPENDS "ament_cmake")
set(dofbot_info_BUILD_EXPORT_DEPENDS )
set(dofbot_info_BUILDTOOL_EXPORT_DEPENDS )
set(dofbot_info_EXEC_DEPENDS )
set(dofbot_info_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(dofbot_info_GROUP_DEPENDS )
set(dofbot_info_MEMBER_OF_GROUPS )
set(dofbot_info_DEPRECATED "")
set(dofbot_info_EXPORT_TAGS)
list(APPEND dofbot_info_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
