from setuptools import find_packages, setup

package_name = "cap_vision"

setup(
    name=package_name,
    version="0.1.0",
    packages=find_packages(exclude=["test"]),
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml"]),
        ("share/" + package_name + "/launch", ["launch/cap_mapping.launch.py", "launch/cubes.launch.py", "launch/sim_red_demo.launch.py", "launch/live_red_track.launch.py", "launch/red_scene.launch.py", "launch/red_scene_system.launch.py", "launch/object_pipeline.launch.py", "launch/cube_6d_camera.launch.py", "launch/world_view.launch.py"]),
        ("share/" + package_name + "/config", [
            "config/camera.yaml",
            "config/homography.yaml",
            "config/camera_info_640x480.yaml",
            "config/table_zones.yaml",
            "config/sim_red.rviz",
            "config/red_scene.yaml",
            "config/cube_6d_urdf.yaml",
            "config/red_scene.rviz",
            "config/world.rviz",
            "config/object_models.yaml",
            "config/cube_color_hsv.yaml",
        ]),
    ],
    # OpenCV/numpy/pyyaml cài ở môi trường Python (apt python3-opencv,
    # python3-numpy, python3-yaml); cv_bridge là ROS package trong image.
    # Không khai báo chúng ở đây để colcon không gọi pip trong lúc build offline.
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="AnhDuy",
    maintainer_email="lehoanhduy5426@gmail.com",
    description="Camera that cho cap_sorting: homography + detect nap + RViz.",
    license="MIT",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "camera_test = cap_vision.camera_test:main",
            "calibrate_table = cap_vision.calibrate_table:main",
            "test_pixel_to_xy = cap_vision.test_pixel_to_xy:main",
            "cap_detector = cap_vision.cap_detector:main",
            "cap_rviz_publisher = cap_vision.cap_rviz_publisher:main",
            "calibrate_intrinsic = cap_vision.calibrate_intrinsic:main",
            "cube_detector = cap_vision.cube_detector:main",
            "cube_localizer = cap_vision.cube_localizer:main",
            "cubes_pick_place = cap_vision.cubes_pick_place:main",
            "zone_markers = cap_vision.zone_markers:main",
            "sim_red_objects = cap_vision.sim_red_objects:main",
            "sim_red_check = cap_vision.sim_red_check:main",
            "sim_red_run = cap_vision.sim_red_run:main",
            "real_red_run = cap_vision.real_red_run:main",
            "cube_tracker = cap_vision.cube_tracker:main",
            "red_scene = cap_vision.red_scene_node:main",
            "red_scene_task = cap_vision.red_scene_task:main",
            "generate_calib_poses = cap_vision.generate_calib_poses:main",
            "validate_mapping = cap_vision.validate_mapping:main",
            "calibrate_eye_in_hand = cap_vision.calibrate_eye_in_hand:main",
            "calibrate_tag_hand_eye = cap_vision.calibrate_tag_hand_eye:main",
            "capture_calibration = cap_vision.capture_calibration:main",
            "collect_tag_hand_eye = cap_vision.collect_tag_hand_eye:main",
            "object_perception = cap_vision.object_perception_node:main",
            "fake_real_joints = cap_vision.fake_real_joints:main",
            "real_joint_mirror = cap_vision.real_joint_mirror:main",
            "train_object_segmenter = cap_vision.train_object_segmenter:main",
            "validate_tag_model = cap_vision.validate_tag_model:main",
            "snapshot_topic = cap_vision.snapshot_topic:main",
            "collect_instance_dataset = cap_vision.collect_instance_dataset:main",
            "world_publisher = cap_vision.world_publisher:main",
        ],
    },
)
