set(_AMENT_PACKAGE_NAME "dofbot_interface")
set(dofbot_interface_VERSION "0.0.0")
set(dofbot_interface_MAINTAINER "yahboom <yahboom@todo.todo>")
set(dofbot_interface_BUILD_DEPENDS "rosidl_default_generators" "geometry_msgs" "std_msgs")
set(dofbot_interface_BUILDTOOL_DEPENDS "ament_cmake")
set(dofbot_interface_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs")
set(dofbot_interface_BUILDTOOL_EXPORT_DEPENDS )
set(dofbot_interface_EXEC_DEPENDS "rosidl_default_runtime" "geometry_msgs" "std_msgs")
set(dofbot_interface_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(dofbot_interface_GROUP_DEPENDS )
set(dofbot_interface_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(dofbot_interface_DEPRECATED "")
set(dofbot_interface_EXPORT_TAGS)
list(APPEND dofbot_interface_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
