# Camera that cho cap_sorting. Load boi camera_test + cap_detector.
cap_vision:
  ros__parameters:
    device_index: 10      # /dev/video10 OBS-VirtualCam DroidCam
    width: 1280
    height: 720
    fps: 30.0
    frame_id: "camera_frame"
    image_topic: "/cap_vision/image_raw"
